# Generated by Django 4.2.7 on 2024-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('subscribers', models.IntegerField()),
                ('increment', models.IntegerField()),
                ('post_views', models.IntegerField()),
                ('er', models.FloatField()),
                ('references', models.IntegerField()),
                ('geo', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'image')},
            },
        ),
    ]
