# Generated by Django 5.0.3 on 2024-03-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parsedchannel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedchannel',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
